const integrante = [
    {
        id: "1",
        img: "./assets/PROFILE-BIANCA.jpeg",
        nombre: "Mariela González",
        descripcion: "Desarrolladora Full Stack y profesora de inglés con un gusto especial por el Frontend. ¡Transformando grandes ideas en código desde la pasión por el aprendizaje!",
        git: "https://github.com/marielabi",
        linkedin: "https://www.linkedin.com/in/mariela-gonz%C3%A1lez-814abb2b8/",
    },
    {
        id: "2",
        img: "./assets/PROFILE-CINTHYA.png",
        nombre: "Cinthya Gómez",
        descripcion: "Soy una desarrolladora Java Full Stack Jr. con formación en Matemáticas Aplicadas y Computación. Combino habilidades técnicas con un enfoque analítico y creativo",
        git: "https://github.com/CinthyaAbigailGomezCarreto",
        linkedin: "https://www.linkedin.com/in/cinthya-abigail-gomez",
    },
    {
        id: "3",
        img: "./assets/PROFILE-ANDY.png",
        nombre: "Andrea Sánchez",
        descripcion: "Ingeniera mecatrónica con interés en el área de desarrollo, con gusto por la literatura, la danza y amante del café. Mi bebé tiene 4 patitas y se llama Chaparringuis.",
        git: "https://github.com/Andrea-SST ",
        linkedin: "https://www.linkedin.com/in/andrea-susana-sanchez-torres-a145a6207/ ",
    },
    {
        id: "4",
        img: "./assets/PROFILE-SANDY.png",
        nombre: "Sandra Hernández",
        descripcion: "Desarrolladora Java Full Stack y Bióloga molecular. Amante de la tecnología, las ciencias, las artes, y claro, de nuestros queridos compañeros peludos. Mi vida está impulsada por la pasión de crear cosas nuevas, y qué mejor manera de hacerlo que a través del código.",
        git: "https://github.com/sandracirnes",
        linkedin: "https://www.linkedin.com/in/sandra-hs/",
    },
    {
        id: "5",
        img: "./assets/PROFILE-XIME.jpeg",
        nombre: "Ximena Juárez",
        descripcion: "Apasionada por leer y aprender para compartirlo en donde se pueda. Para mi las TI son un puente que conecta y reduce brechas.",
        git: "https://github.com/ximejm",
        linkedin: "https://www.linkedin.com/in/ximena-ju%C3%A1rez-142178a9/",
    },
    {
        id: "6",
        img: "./assets/PROFILE-AMARANTHA-Photoroom.jpg",
        nombre: "Amarantha Hernández",
        descripcion: "Ingeniera en mecatrónica con pasión por la tecnología, inmersa en el área de Java Full Stack Jr., demostrando compromiso con el aprendizaje continuo.",
        git: "https://github.com/AmaranthaH",
        linkedin: "https://www.linkedin.com/in/amarantha-hernandez-ricardez/",
    },
    {
        id: "7",
        img: "./assets/Porfile Kenia Estrada (1).jpg",
        nombre: "Kenia Estrada",
        descripcion: "Desarrolladora Java Full stack y Química Farmacéutica Bióloga con habilidades en documentación, análisis de datos y resolución de problemas, con capacidad para aportar una perspectiva única en el diseño y desarrollo de softwares.",
        git: "https://github.com/keniaestrada",
        linkedin: "linkedin.com/in/kenia-texcalpa target=",
    },
    {
        id: "8",
        img: "./assets/PROFILE-VIRY.png",
        nombre: "Viridiana Castillo",
        descripcion: "Farmacéutica apasionada por la salud, la ciencia, la danza y el cheerleading, explorando y desarrollándome en el universo TI para convertir mis sueños más salvajes en realidad.",
        git: "https://github.com/Viriiviriibamba",
        linkedin: "https://mx.linkedin.com/in/dulce-viridiana-castillo-martinez",
    },
    {
        id: "9",
        img: "./assets/Profile-Nancy (1).jpg",
        nombre: "Nancy Galicia",
        descripcion: "Ing. en Sistemas Inteligentes, con experiencia, en IAM,busco desarrollarme profesionalmente como Desarrolladora Front-End",
        git: "https://github.com/ncgalicia",
        linkedin: "https://www.linkedin.com/in/yareli-galicia",
    },
];

const pawfriend = [
    {
        id: "1",
        img: "./assets/PAWAMIGO-CINTHYA.jpg",
        nombre: "Pecas",
        descripcion: "El gato mas guapo (y consentido ¬¬) del mundo mundial!!!",
    },
    {
        id: "2",
        img: "./assets/PAWAMIGO-CINTHYA.jpg",
        nombre: "Pecas",
        descripcion: "El gato mas guapo (y consentido ¬¬) del mundo mundial!!!",
    },
    {
        id: "3",
        img: "./assets/PAWAMIGO-ANDREA.JPG",
        nombre: "Chaparringuis",
        descripcion: "Me encanta jugar, correr y comer",
    },
    {
        id: "4",
        img: "./assets/PAWAMIGO-SANDRA.png",
        nombre: "Kyrie y Dixie",
        descripcion: "Nos encanta dormir, hacer berriche y pelearnos entre nosotras",
    },
    {
        id: "5",
        img: "./assets/PAWAMIGO-XIMENA.jpg",
        nombre: "Kiara",
        descripcion: "Mi cosa favorita en el mundo son los paseos matutinos",
    },
    {
        id: "6",
        img: "./assets/PAWAMIGO-AMARANTHA.png",
        nombre: "Ninfa",
        descripcion: "Solo como, duermo y grito",
    },
    {
        id: "7",
        img: "./assets/PAWAMIGO-KENIA.jpg",
        nombre: "Deimon y Baby-nejo",
        descripcion: "Nos encanta correr, dormir y jugar juntos.",
    },
    {
        id: "8",
        img: "./assets/PAWAMIGO-VIRI.png",
        nombre: "Capuchina",
        descripcion: "Me gusta comer migajón, paletas heladas, dormir y ver la tele con mi papá",
    },
    {
        id: "9",
        img: "./assets/PAWAMIGO",
        nombre: "Pecas",
        descripcion: "El gato mas guapo (y consentido ¬¬) del mundo mundial!!!",
    },
];